name: Build and Deploy to Droplet

on:
  push:
    branches:
      - dev # Replace with the branch you want to trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Add remote host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DROPLET_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          envs: EMAIL_USER, EMAIL_PASS
          script: |
            set -e
            sudo apt-get update
            sudo apt-get install -y nodejs npm git
            sudo rm -rf /var/www/ece435final.thibodeau.dev
            sudo mkdir -p /var/www/ece435final.thibodeau.dev
            cd /var/www/ece435final.thibodeau.dev
            git clone -b dev https://github.com/JacquesLJT/Portfolio_v2.git .
            npm install
            export EMAIL_USER=${{ secrets.EMAIL_USER }}
            export EMAIL_PASS=${{ secrets.EMAIL_PASS }}
            npm run build
            npm install -g pm2
            pm2 start npm --name "ece435final" -- run start
            sudo systemctl restart apache2
